---
name: "Golang lint"

on:
  release:
    types: [published]
  push:
    branches: ["**"]
    tags: ["v*"]
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  golangci:
    name: "Golang lint"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: "Golang lint"
        uses: golangci/golangci-lint-action@v9
