name: "Test"

on:
  release:
    types: [published]
  push:
    branches: ["master", "dev"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: "Run Tests"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Setup Go"
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true

      - name: "Run Tests"
        run: go test -timeout 1h -v ./...
